### ISSUE TITLE
Had troubles getting the code to run - see below

### ISSUE THREAD

**Issue by jjkirn** [fireship-io/node-blockchain#1]
jim@blockchain:~/Desktop/dev/node-blockchain$ npm start

> blockchain@1.0.0 start /home/jim/Desktop/dev/node-blockchain
> tsc && node .

⛏️  mining...

<--- Last few GCs --->

[3125:0x8299a0]    48929 ms: Mark-sweep 1373.9 (1425.5) -> 1373.8 (1425.5) MB, 2545.5 / 25.8 ms  (average mu = 0.188, current mu = 0.234) allocation failure GC in old space requested
[3125:0x8299a0]    53388 ms: Mark-sweep 1374.5 (1425.5) -> 1374.3 (1426.0) MB, 3740.9 / 8.6 ms  (average mu = 0.173, current mu = 0.161) allocation failure GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1a042de5452b]
    1: StubFrame [pc: 0x1a042dd9a1f0]
    2: ConstructFrame [pc: 0x1a042dd99d43]
Security context: 0x36207fcaee11 <JSObject>
    3: Transform [0x805070824c9] [_stream_transform.js:~104] [pc=0x1a042dd84ad6](this=0x2f6cb16f6659 <Hash map = 0x1174a4df04c1>,options=0x30cebff825d9 <undefined>)
    4: mine [0xf816fe09011] [/home/jim/Desktop/dev/node-blockchain/index.js:~64] [pc=0x1a042df10ebe](this=0x0f816f...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7fb5f35b546c node::Abort() [/lib/x86_64-linux-gnu/libnode.so.64]
 2: 0x7fb5f35b54b5  [/lib/x86_64-linux-gnu/libnode.so.64]
 3: 0x7fb5f37e1e6a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 4: 0x7fb5f37e20e1 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 5: 0x7fb5f3b7cc66  [/lib/x86_64-linux-gnu/libnode.so.64]
 6: 0x7fb5f3b8e043 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 7: 0x7fb5f3b8e930 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 8: 0x7fb5f3b9091d v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
 9: 0x7fb5f3b90975 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
10: 0x7fb5f3b5cdda v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/lib/x86_64-linux-gnu/libnode.so.64]
11: 0x7fb5f3de831e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/lib/x86_64-linux-gnu/libnode.so.64]
12: 0x1a042de5452b 
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! blockchain@1.0.0 start: `tsc && node .`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the blockchain@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jim/.npm/_logs/2021-03-03T01_14_52_067Z-debug.log

**Comment by a2br** [comment]
SO is your best friend. It looks like a memory allocation problem: https://stackoverflow.com/a/46689037/13230118

**Comment by jjkirn** [comment]
Looked over the "increase-memory-limit" advice at https://www.npmjs.com/package/increase-memory-limit
Set "export NODE_OPTIONS=--max_old_space_size=12000
Re-sized my Ubuntu 20.04 Desktop VM to 16GB RAM and ran "npm start"
Ran "top" while it was running - it consumed over 15GM of RAM before it crashed.
![RAM Usage 3](https://user-images.githubusercontent.com/29265266/109839830-21e4e480-7c0d-11eb-85cb-48787c923d77.png)
Here is the crash info: 
![Crash](https://user-images.githubusercontent.com/29265266/109840144-712b1500-7c0d-11eb-8b28-39e7e0da96a1.png)

Not sure where to go from here - gave it 16GB RAMm 4 CPUs - still crashes!

**Comment by a2br** [comment]
Oh, this may be an issue with your VM, maybe you should try it on Windows
